language: ruby
rvm:
 - 2.3
before_deploy:
  - git config --local user.name "Travis Build Server"
  - git config --local user.email "superterran@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: rubygems
  api_key: $RUBYGEMS_API_KEY
  skip_cleanup: true
  on:
    all_branches: true
deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file_glob: true
  file: jekyll-thumbnail-*.gem