language: ruby
rvm:
 - 2.3
deploy:
  provider: rubygems
  api_key: $RUBYGEMS_API_KEY
  skip_cleanup: true
  on:
    all_branches: true
deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file_glob: true
  file: jekyll-thumbnail-*.gem